### ISSUE TITLE
Add A Runit Service

### ISSUE THREAD

**Issue by TheCatster** [MrPotatoBobx/FetchCord#75]
Having a runit service would be great for all my fellow Artix and Void users, and doesn't seem to difficult to implement since a systemd service already exists.

Thanks!

**Comment by Hyper-KVM** [comment]
Yeah I attempted to make an runit service, only problem is....the service cannot see the discord process (since it's a system service) aaaand wouldn't work at all. That said, it may be possible to make a user service with a user dir but I just settled for a discord script that launches both and closes them if one or the other gets closed. I could add it to the repo I guess.

**Comment by TheCatster** [comment]
That'd be good enough for now, although it would be interesting to figure it out at a system level. I might prod at it as well.

**Comment by Hyper-KVM** [comment]
Okay, can do.
